/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WritingRouteImport } from './routes/writing'
import { Route as WorkRouteImport } from './routes/work'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as WritingSlugRouteImport } from './routes/writing.$slug'
import { Route as WorkSlugRouteImport } from './routes/work.$slug'
import { Route as VideosSlugRouteImport } from './routes/videos.$slug'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as AdminWritingIndexRouteImport } from './routes/admin.writing.index'
import { Route as AdminWorkIndexRouteImport } from './routes/admin.work.index'
import { Route as AdminVideosIndexRouteImport } from './routes/admin.videos.index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin.users.index'
import { Route as AdminCoursesIndexRouteImport } from './routes/admin.courses.index'
import { Route as AdminWritingIdRouteImport } from './routes/admin.writing.$id'
import { Route as AdminWorkIdRouteImport } from './routes/admin.work.$id'
import { Route as AdminVideosIdRouteImport } from './routes/admin.videos.$id'
import { Route as AdminCoursesIdRouteImport } from './routes/admin.courses.$id'

const WritingRoute = WritingRouteImport.update({
  id: '/writing',
  path: '/writing',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const WritingSlugRoute = WritingSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WritingRoute,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WorkRoute,
} as any)
const VideosSlugRoute = VideosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => VideosRoute,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CoursesRoute,
} as any)
const AdminWritingIndexRoute = AdminWritingIndexRouteImport.update({
  id: '/writing/',
  path: '/writing/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWorkIndexRoute = AdminWorkIndexRouteImport.update({
  id: '/work/',
  path: '/work/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVideosIndexRoute = AdminVideosIndexRouteImport.update({
  id: '/videos/',
  path: '/videos/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesIndexRoute = AdminCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWritingIdRoute = AdminWritingIdRouteImport.update({
  id: '/writing/$id',
  path: '/writing/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWorkIdRoute = AdminWorkIdRouteImport.update({
  id: '/work/$id',
  path: '/work/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVideosIdRoute = AdminVideosIdRouteImport.update({
  id: '/videos/$id',
  path: '/videos/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesIdRoute = AdminCoursesIdRouteImport.update({
  id: '/courses/$id',
  path: '/courses/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/courses': typeof CoursesRouteWithChildren
  '/videos': typeof VideosRouteWithChildren
  '/work': typeof WorkRouteWithChildren
  '/writing': typeof WritingRouteWithChildren
  '/courses/$slug': typeof CoursesSlugRoute
  '/videos/$slug': typeof VideosSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/courses/$id': typeof AdminCoursesIdRoute
  '/admin/videos/$id': typeof AdminVideosIdRoute
  '/admin/work/$id': typeof AdminWorkIdRoute
  '/admin/writing/$id': typeof AdminWritingIdRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/videos/': typeof AdminVideosIndexRoute
  '/admin/work/': typeof AdminWorkIndexRoute
  '/admin/writing/': typeof AdminWritingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/courses': typeof CoursesRouteWithChildren
  '/videos': typeof VideosRouteWithChildren
  '/work': typeof WorkRouteWithChildren
  '/writing': typeof WritingRouteWithChildren
  '/courses/$slug': typeof CoursesSlugRoute
  '/videos/$slug': typeof VideosSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/courses/$id': typeof AdminCoursesIdRoute
  '/admin/videos/$id': typeof AdminVideosIdRoute
  '/admin/work/$id': typeof AdminWorkIdRoute
  '/admin/writing/$id': typeof AdminWritingIdRoute
  '/admin/courses': typeof AdminCoursesIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/videos': typeof AdminVideosIndexRoute
  '/admin/work': typeof AdminWorkIndexRoute
  '/admin/writing': typeof AdminWritingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/courses': typeof CoursesRouteWithChildren
  '/videos': typeof VideosRouteWithChildren
  '/work': typeof WorkRouteWithChildren
  '/writing': typeof WritingRouteWithChildren
  '/courses/$slug': typeof CoursesSlugRoute
  '/videos/$slug': typeof VideosSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/courses/$id': typeof AdminCoursesIdRoute
  '/admin/videos/$id': typeof AdminVideosIdRoute
  '/admin/work/$id': typeof AdminWorkIdRoute
  '/admin/writing/$id': typeof AdminWritingIdRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/videos/': typeof AdminVideosIndexRoute
  '/admin/work/': typeof AdminWorkIndexRoute
  '/admin/writing/': typeof AdminWritingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/courses'
    | '/videos'
    | '/work'
    | '/writing'
    | '/courses/$slug'
    | '/videos/$slug'
    | '/work/$slug'
    | '/writing/$slug'
    | '/admin/'
    | '/admin/courses/$id'
    | '/admin/videos/$id'
    | '/admin/work/$id'
    | '/admin/writing/$id'
    | '/admin/courses/'
    | '/admin/users/'
    | '/admin/videos/'
    | '/admin/work/'
    | '/admin/writing/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/courses'
    | '/videos'
    | '/work'
    | '/writing'
    | '/courses/$slug'
    | '/videos/$slug'
    | '/work/$slug'
    | '/writing/$slug'
    | '/admin'
    | '/admin/courses/$id'
    | '/admin/videos/$id'
    | '/admin/work/$id'
    | '/admin/writing/$id'
    | '/admin/courses'
    | '/admin/users'
    | '/admin/videos'
    | '/admin/work'
    | '/admin/writing'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/courses'
    | '/videos'
    | '/work'
    | '/writing'
    | '/courses/$slug'
    | '/videos/$slug'
    | '/work/$slug'
    | '/writing/$slug'
    | '/admin/'
    | '/admin/courses/$id'
    | '/admin/videos/$id'
    | '/admin/work/$id'
    | '/admin/writing/$id'
    | '/admin/courses/'
    | '/admin/users/'
    | '/admin/videos/'
    | '/admin/work/'
    | '/admin/writing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  VideosRoute: typeof VideosRouteWithChildren
  WorkRoute: typeof WorkRouteWithChildren
  WritingRoute: typeof WritingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/writing': {
      id: '/writing'
      path: '/writing'
      fullPath: '/writing'
      preLoaderRoute: typeof WritingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/writing/$slug': {
      id: '/writing/$slug'
      path: '/$slug'
      fullPath: '/writing/$slug'
      preLoaderRoute: typeof WritingSlugRouteImport
      parentRoute: typeof WritingRoute
    }
    '/work/$slug': {
      id: '/work/$slug'
      path: '/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof WorkRoute
    }
    '/videos/$slug': {
      id: '/videos/$slug'
      path: '/$slug'
      fullPath: '/videos/$slug'
      preLoaderRoute: typeof VideosSlugRouteImport
      parentRoute: typeof VideosRoute
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/admin/writing/': {
      id: '/admin/writing/'
      path: '/writing'
      fullPath: '/admin/writing/'
      preLoaderRoute: typeof AdminWritingIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/work/': {
      id: '/admin/work/'
      path: '/work'
      fullPath: '/admin/work/'
      preLoaderRoute: typeof AdminWorkIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/videos/': {
      id: '/admin/videos/'
      path: '/videos'
      fullPath: '/admin/videos/'
      preLoaderRoute: typeof AdminVideosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses/': {
      id: '/admin/courses/'
      path: '/courses'
      fullPath: '/admin/courses/'
      preLoaderRoute: typeof AdminCoursesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/writing/$id': {
      id: '/admin/writing/$id'
      path: '/writing/$id'
      fullPath: '/admin/writing/$id'
      preLoaderRoute: typeof AdminWritingIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/work/$id': {
      id: '/admin/work/$id'
      path: '/work/$id'
      fullPath: '/admin/work/$id'
      preLoaderRoute: typeof AdminWorkIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/videos/$id': {
      id: '/admin/videos/$id'
      path: '/videos/$id'
      fullPath: '/admin/videos/$id'
      preLoaderRoute: typeof AdminVideosIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses/$id': {
      id: '/admin/courses/$id'
      path: '/courses/$id'
      fullPath: '/admin/courses/$id'
      preLoaderRoute: typeof AdminCoursesIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCoursesIdRoute: typeof AdminCoursesIdRoute
  AdminVideosIdRoute: typeof AdminVideosIdRoute
  AdminWorkIdRoute: typeof AdminWorkIdRoute
  AdminWritingIdRoute: typeof AdminWritingIdRoute
  AdminCoursesIndexRoute: typeof AdminCoursesIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminVideosIndexRoute: typeof AdminVideosIndexRoute
  AdminWorkIndexRoute: typeof AdminWorkIndexRoute
  AdminWritingIndexRoute: typeof AdminWritingIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminCoursesIdRoute: AdminCoursesIdRoute,
  AdminVideosIdRoute: AdminVideosIdRoute,
  AdminWorkIdRoute: AdminWorkIdRoute,
  AdminWritingIdRoute: AdminWritingIdRoute,
  AdminCoursesIndexRoute: AdminCoursesIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminVideosIndexRoute: AdminVideosIndexRoute,
  AdminWorkIndexRoute: AdminWorkIndexRoute,
  AdminWritingIndexRoute: AdminWritingIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CoursesRouteChildren {
  CoursesSlugRoute: typeof CoursesSlugRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesSlugRoute: CoursesSlugRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

interface VideosRouteChildren {
  VideosSlugRoute: typeof VideosSlugRoute
}

const VideosRouteChildren: VideosRouteChildren = {
  VideosSlugRoute: VideosSlugRoute,
}

const VideosRouteWithChildren =
  VideosRoute._addFileChildren(VideosRouteChildren)

interface WorkRouteChildren {
  WorkSlugRoute: typeof WorkSlugRoute
}

const WorkRouteChildren: WorkRouteChildren = {
  WorkSlugRoute: WorkSlugRoute,
}

const WorkRouteWithChildren = WorkRoute._addFileChildren(WorkRouteChildren)

interface WritingRouteChildren {
  WritingSlugRoute: typeof WritingSlugRoute
}

const WritingRouteChildren: WritingRouteChildren = {
  WritingSlugRoute: WritingSlugRoute,
}

const WritingRouteWithChildren =
  WritingRoute._addFileChildren(WritingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CoursesRoute: CoursesRouteWithChildren,
  VideosRoute: VideosRouteWithChildren,
  WorkRoute: WorkRouteWithChildren,
  WritingRoute: WritingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
